# Generated by Django 4.2.27 on 2026-01-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_studentprofile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='public_profile',
            field=models.BooleanField(default=False, help_text='If true, profile is publicly viewable by username'),
        ),
    ]
