# Generated by Django 4.2.27 on 2026-01-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_studentprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='instructor_photos/'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='public_profile',
            field=models.BooleanField(default=False, help_text='If true, instructor profile is publicly viewable by username'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma separated skills'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
