# Generated by Django 4.2.27 on 2026-01-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_instructorprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='bank_swift',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='InstructorSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, max_length=500)),
                ('twitter', models.URLField(blank=True, max_length=500)),
                ('github', models.URLField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='profiles.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='profiles.instructorprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profiles.instructorprofile')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='instructor_certificates/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='profiles.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='profiles.instructorprofile')),
            ],
        ),
    ]
