# Generated by Django 5.2.10 on 2026-01-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category_course_slug_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='passing_score',
            field=models.IntegerField(blank=True, help_text='Passing percentage', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_type',
            field=models.CharField(blank=True, choices=[('Multiple Choice', 'Multiple Choice'), ('Short Answer', 'Short Answer'), ('Essay', 'Essay'), ('Mixed', 'Mixed')], default='Multiple Choice', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resource_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
