# Generated by Django 5.2.10 on 2026-01-16 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft_skills', 'Soft Skills'), ('management', 'Management')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='profiles.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completion_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='profiles.studentprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='trainings.trainingprogram')),
            ],
            options={
                'unique_together': {('student', 'program')},
            },
        ),
    ]
