# Generated by Django 5.2.10 on 2026-01-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='duration_hours',
            field=models.IntegerField(default=2, help_text='Training duration in hours'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='instructor_email',
            field=models.EmailField(blank=True, help_text='Instructor contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='instructor_name',
            field=models.CharField(blank=True, help_text='Name of the training instructor', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='live_link',
            field=models.URLField(blank=True, help_text='Join link for live training session (e.g., Zoom, Google Meet, Teams)', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='live_status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='max_participants',
            field=models.IntegerField(default=100, help_text='Maximum number of participants'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Prerequisites or requirements'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='recording_link',
            field=models.URLField(blank=True, help_text='Link to training session recording', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='resource_link',
            field=models.URLField(blank=True, help_text='Link to training materials/documents', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='When the training is scheduled', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
