# Generated by Django 5.2.10 on 2026-01-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Update', 'Update'), ('Enrollment', 'Enrollment'), ('Alert', 'Alert')], default='Update', max_length=20),
        ),
    ]
