# Generated by Django 5.2.10 on 2026-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Update', 'Update'), ('Enrollment', 'Enrollment'), ('Alert', 'Alert'), ('Course_Creation', 'Course Creation')], default='Update', max_length=20),
        ),
    ]
